create extension if not exists pg_trgm with schema extensions;

create table public.cities (
  id bigint generated by default as identity primary key,
  geonames_id bigint not null unique check (geonames_id > 0),
  name text not null check (length(btrim(name)) > 0),
  country_code text not null check (country_code ~ '^[A-Z]{2}$'),
  region text,
  timezone text not null check (
    length(btrim(timezone)) > 0
    and timezone ~ '^[A-Za-z_+-]+(/[A-Za-z0-9_+-]+)+$'
  ),
  latitude numeric(9, 6) not null check (latitude between -90 and 90),
  longitude numeric(9, 6) not null check (longitude between -180 and 180),
  population bigint check (population is null or population >= 0),
  description text,
  image_url text,
  cost_index numeric(3, 2) check (cost_index is null or cost_index between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index cities_normalized_name_country_key
on public.cities (lower(btrim(name)), country_code);

create index cities_name_search_idx
on public.cities using gin (lower(name) extensions.gin_trgm_ops);

create index cities_region_search_idx
on public.cities using gin (lower(coalesce(region, '')) extensions.gin_trgm_ops);

create table public.activities (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.cities (id),
  fsq_place_id text not null unique check (length(btrim(fsq_place_id)) > 0),
  name text not null check (length(btrim(name)) > 0),
  category text not null check (
    category in ('sightseeing', 'food', 'adventure', 'culture', 'nightlife', 'other')
  ),
  provider_category_id text,
  provider_category_name text,
  description text,
  latitude numeric(9, 6) not null check (latitude between -90 and 90),
  longitude numeric(9, 6) not null check (longitude between -180 and 180),
  image_url text,
  duration_minutes integer check (duration_minutes is null or duration_minutes > 0),
  estimated_cost numeric(12, 2) check (estimated_cost is null or estimated_cost >= 0),
  currency_code text check (currency_code is null or currency_code ~ '^[A-Z]{3}$'),
  price_tier smallint check (price_tier is null or price_tier between 1 and 4),
  rating numeric(3, 1) check (rating is null or rating between 0 and 10),
  provider_popularity numeric(5, 4) check (
    provider_popularity is null or provider_popularity between 0 and 1
  ),
  provider_synced_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activities_cost_currency_check check (
    estimated_cost is null or currency_code is not null
  )
);

create index activities_city_id_idx on public.activities (city_id);
create index activities_category_idx on public.activities (category);
create index activities_name_search_idx
on public.activities using gin (lower(name) extensions.gin_trgm_ops);

create function private.touch_catalog_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke execute on function private.touch_catalog_updated_at() from public;

create trigger touch_cities_updated_at
before update on public.cities
for each row
execute function private.touch_catalog_updated_at();

create trigger touch_activities_updated_at
before update on public.activities
for each row
execute function private.touch_catalog_updated_at();

alter table public.cities enable row level security;
alter table public.activities enable row level security;

revoke all on table public.cities, public.activities from anon, authenticated, service_role;
revoke all on sequence public.cities_id_seq, public.activities_id_seq
from anon, authenticated, service_role;

grant select on table public.cities, public.activities to authenticated;

grant select, insert, update, delete on table public.cities, public.activities to service_role;
grant usage, select on sequence public.cities_id_seq, public.activities_id_seq to service_role;

create policy "Authenticated users can read cities"
on public.cities
for select
to authenticated
using (true);

create policy "Authenticated users can read activities"
on public.activities
for select
to authenticated
using (true);
